var jack_bauer_facts = [
	"Nem hörög a paraszt, ha nem szúrja a kés!",
	"Ordít, mint a számba szorult féreg.",
	"A szó elszáll, az írás olvashatatlan.",
	"Részemről a kockahas el van vetve!",
	"Kína teljes lakossága Jack fejét akarja. Fair küzdelem lenne.",
	"Sokat akar a szarka, de menstruál a szarkalány.",
	"A kivétel erősíti a vakbelet.",
	"Kicsi a bors, de nagyot tüsszentesz tőle.",
	"Felesleges, mint Zalatnaynak az utazási katalógus.",
	"Egyik szemem sír, másik meg a koporsó.",
	"Ki korán kel, egész nap álmos.",
	"Olcsó húsnak is emelkedik az ára.",
	"Ajándék ló nem látja a fától a szódás lovát.",
	"Itt van a kutya elesve!",
	"A moha déli oldalán mindig fa van.",
	"Az ismétlés az unalom apja.",
	"Ajándék szesznek ne nézd a fokát!",
	"A lustaság fél egészség, de miért ne legyünk teljesen egészségesek?",
	"Kétféle vélemény van: az enyém és a helytelen.",
	"Ez beütött, mint Quasimodonak a Limbo-láz.",
	"Ajándék lónak híg a leve.",
	"Aki korán kel... hamarabb iszik.",
	"Ha minden kötél szakad, akkor ne félj az akasztófától!",
	"Jobb ma örömmel, mint holnap körömmel. (mosogatás előtt.",
	"Nem esik messze a szódás a lovától.",
	"Amit magadnak kívánsz, ne tedd azt embertársaiddal, hátha más az ízlésük.",
	"A hülyeségnek nincs határa, életcélom azt mégis átlépni.",
	"Ami ingyen van, az biztos megéri az árát.",
	"Nem a világ lett rosszabb, a hírszolgáltatás lett jobb.",
	"Nem bírom nézni, ha szenvednek az emberek. De valamiből nekem is élnem kell - mondta az inkvizítor.",
	"Az angol repülőtéren máris kétszer annyi ember tolong, mint amennyi elfér.",
	"Meteorológiai előrejelzés: előbb-utóbb tavasz lesz.",
	"Ferde fej a divat! Tessék mondani: a gondolat azért lehet egyenes?",
	"Jó munkavédelmi tevékenység: sok baleset!",
	"A szabadstrandot utasaink díjmentesen használhatják.",
	"Minél idősebb egy sportoló, annál sikeresebb volt hajdan.",
	"Az öregkor hamar elszáll. Aztán jön a második fiatalságunk.",
	"Aki tudja, hogyan kell a nehézségekből kilábalni, mindig kevesebbet ér, mint aki azt tudja, hogyan lehet elkerülni őket.",
	"Tévedni emberi dolog. Különösen akkor, ha mi tévedünk.",
	"Ahelyett, hogy egy politikusnak átnyújtanánk a város kulcsait, jobb lenne inkább a zárat kicseréltetni.",
	"Az embernek az az örökös fő hibája, hogy annyi apró hibája van.",
	"Legjobb párna a lelkiismeret.",
	"Túl messzire kell mennünk ahhoz, hogy megtudjuk, milyen messzire mehetünk.",
	"Az az egyetlen baj az egoistákkal, hogy saját maguk jobban érdeklik őket, mint én.",
	"Bármi, amiben egy csöpp élvezet is van, az vagy erkölcstelen, vagy törvénysértő, vagy hízlal.",
	"A teve olyan ló, amit egy bizottság tervezett.",
	"Le a gravitációval!",
	"A kannibál nem vegetáriánus, hanem humanitáriánus.",
	"Csak egyszer vagyunk fiatalok. Utána más mentséget kell találnunk.",
	"Csak a bolondok veszik magukat igazán komolyan.",
	"A helyzet reménytelen, de nem súlyos.",
	"A remény az az érzés, hogy ez az érzés nem tartós.",
	"Nem hiszek a túlvilágban, de azért van nálam egy váltás alsónemű.",
	"Az a legszebb a kopaszságban, hogy az ember hallja a hópelyheket.",
	"A teológia a vallásnak az a része, amihez ész is kell.",
	"Az emberek törvényt mondanak, de vagyonra gondolnak.",
	"A vezér ne előzze meg nagyon a csapatát, mert seggbelövik.",
	"Nincs annál jobb vicc, mint amit az ember a beosztottjainak mesél.",
	"Semmi sem okozhat nagyobb kárt, mint egy olyan hazugság, amelyik hasonlít az igazsághoz.",
	"A szellemesség művelt pimaszság.",
	"Az ellentétek vonzzák a... problémákat!",
	"Jobb ma egy veréb és még nem is túlzok!",
	"Aki a meleget szereti, hóember nem lehet.",
	"A suszter maradjon annál a fánál, amelyiket KAPTA.",
	"Nem minden arany, ami hörcsög!",
	"Jobb kefélni, mint megijedni.",
	"Okos ember más feleségén tanul.",
	"Addig még sok cián lefolyik a Tiszán.",
	"A majom nem esik messze a fájától.",
	"Szegény ember kézzel nőz.",
	"A pénz beszél. Azt mondja, viszlát.",
	"Meglátni és megutálni egy pillanat műve volt csupán.",
	"Amit ma megtehetsz, halaszd holnapra, hátha addigra valaki megcsinálja helyetted.",
	"Jó munkához idő kell, rossz munkához még több.",
	"Gondolkodom, tehát vagyok. (Rene Descartes)\nGondolkodom, tehát vagyok-gondolom. (Howard Schneider)",
	"Az élet nem mindig kellemes, de lidércnyomásnak megjárja.",
	"Ritka, mint a fehér Zorro.",
	"Nem szégyen a futás, de a kurva annyát annak aki kerget!",
	"Azt mondják, jó munkához idő kell, de az idő pénz, a pénz nem boldogít. Tehát: a jó munka nem boldogít.",
	"Nem akarásnak nyögés a vége - de ez a szexre nem vonatkozik.",
	"Ne halaszd holnapra, amit meghatározatlan időre elnapolhatsz.",
	"Korán keltem, hol az aranyam?",
	"Aki mer, annál van a kanál.",
	"Kicsi a bors, de főleg az őrölt.",
	"Ízlések és rokonok.",
	"Koreai közmondás: kutyából nem lesz szalonna. Csak rántott hús!",
	"Éhes makkal disznókat álmodsz!",
	"A szó elszáll, írni meg nem tudok.",
	"Ritka, mint a hintalószar!",
	"Ha megdobnak kővel, dobd vissza kettővel.",
	"Aki másnak vermet ás, ... nem magának ássa!",
	"Jobb ma egy veréb, mintha holnap púzok...",
	"Nem a győzelem a fontos, hanem az őszinte részvétem.",
	"Közös lónak túrós a táska.",
	"Madarat tolláról, zoknit szagáról.",
	"Nem a győzelem, a részvétel, hanem a fontos.",
	"Ahány ház, annyi baj legyen.",
	"Jobb ma egy szemüveg, mint holnap egy üvegszem.",
	"Jobb kétszer pofára esni, mint egyszer mellé.",
	"Messziről jött ember akkor hazudik, ha nem jönnek rá.",
	"Okos enged, ha már szenved...",
	"Ki korán kel, nem bír sokáig fennmaradni!",
	"Nem esik messze a vak a botjától!",
	"Szegény ember vizel és főz!",
	"Aki másnak vermet ás, sírásó vagy földmunkás!",
	"Jobb félni, mint megnősülni!",
	"Jön még kutyára teherautó!",
	"A szomszéd sírján mindig zöldebb a fű!",
	"Aki utoljára nevet, az valószínűleg nem értette a viccet.",
	"Ki a hideget nem szereti, hóember nem lehet.",
	"Jobb ma egy alkoholmérgezés, mint holnap egy szívroham.",
	"A nagyhal bekapja a kishalat, a kishal meg bekaphatja a nagyhalét.",
	"Mindenhol jó, de legolcsóbb otthon.",
	"Munka helyett édes a pihenés!",
	"Büdös gyereknek anyja is érzi a szagát.",
	"Nem a részvétel, a győzelem a fontos.",
	"Hajléktalanok jelmondata: \"Kukából nem lesz szalonna.\"",
	"Addig jár a korsó a kútra, míg be nem vezetik a vezetékes vizet.",
	"Felesleges, mint szőkének gondolkodási időt adni.",
	"Közös mosógépnek vízköves a csőrendszere.",
	"Közös számítógépnek tele van a gyökérkönyvtára.",
	"Bízzál Istenben, és mentsél rendszeresen!",
	"Vág az esze, mint az intelligens mosópornak.",
	"Amilyen a login, olyan a bejelentkező képernyő.",
	"Floppyról bootolt (azelőtt: bal lábbal kelt fel).",
	"Ravasz, mint a sakkautomata.",
	"Bolhából elefántot csinál. Vizibolhából meg elefántfókát.",
	"Inkább legyek gazdag és egészséges, mint beteg és szegény!!",
	"Jobb ma egy túzok, meg holnap is!",
	"Verés közben jön-megy a székláb.",
	"Evés közben jön meg a szomszéd.",
	"Akasztott embernek lába se éri a földet.",
	"Közös számítógépnek tele van a gyökérkönyvtára.",
	"Mutasd a háttérképed, megmondom, ki vagy!",
	"Szövegszerkesztőből nem lesz vírusölő.",
	"A szomszéd gépe mindig gyorsabb.",
	"Ép hardverben ép szoftver.",
	"Messziről jött ember sokára ér ide.",
	"Néma gyereknek az anyja se látja a fától az erdőt.",
	"Ahány ház, annyi szopás.",
	"Jó bornak nem kell pohár!",
	"Jó bor is megárt a sok!",
	"Meghalt a király, kis helyen is elfér!",
	"Esze semmi, dugd meg jól!",
	"Aki a kicsit nem becsüli, annak nagy van.",
	"Jobb ma egy veréb, mint holnap egy véreb.",
	"Kicsi a bors, de vannak barátai!",
	"Kicsi a bors, de hol a fenében van?",
	"Hazug embert hamarabb utolérik, ha sánta.",
	"Sok jó ember kis helyen rosszá válik.",
	"Az ígéret szép szó, de a Landwirtschaftsausstellung még szebb!",
	"Néma gyereknek anyja veri a farkát!",
	"Néma gyereknek anyja se vesz telefonkártyát!",
	"Nem esik messze a vak a botjától.",
	"Aki mer, az nyer - Aki merít, az nyerít?",
	"Aki nem hiszi, járjon ruhába!",
	"Hülye vagy, mint a szódás a lovát!",
	"Aki a kicsit nem becsüli, az simogassa.",
	"Kicsi a bors, de tényleg."
];

var getAFact = function() {
	// check if we're out of facts to avoid an indexOutOfBounds exception
	if(jack_bauer_facts.length === 0) {
		// all the facts have been seen, tell user that they're done.
		$("#fact").text("A féligazságnak rendszerint még a fele sem igaz.");
	} else {
		// there are still facts in the array, so picks a random one
		var index = Math.floor(Math.random() * jack_bauer_facts.length);
		$("#fact").text(jack_bauer_facts[index]);

		// remove this fact from the facts list to avoid repeating facts
		jack_bauer_facts.splice(index, 1);
	}
}

// set up handler for when random fact button clicked
$("#random_fact").click(getAFact);

// initialize text
getAFact();
